apiVersion: v1
kind: Service
metadata:
  name: mimas-svc
  namespace: devops
spec:
  selector:
    app: mimascompany
  type: NodePort
  ports:
  - name: mimas-port
    protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 32031
